### ISSUE TITLE
!.unknown_video extension download fails

### ISSUE THREAD

**Issue by kasslover530** [mariosemes/PornHub-downloader-python#47]
Hi,

I believe the PH streaming algorithm changed. The code does not work anymore and outputs 
".unknown_video" file extension of ~1.37kb

**Comment by vlanes2** [comment]
It has indeed... I did have a little better luck after updating Youtube-DL to 04.07.2021... BUT
it will download m3u8 instead of mp4 from model pages (you can just mass-rename to mp4 and it works perfectly fine). But I'm realizing that it keeps getting stuck on these loops. Hoping that the fix will come soon, absolutely love this project.

**Comment by lynxbmw** [comment]
in requirement.txt change
youtube-dl==2020.1.1
to
youtube-dl==2021.03.03

Do
pip3 install -r requirements.txt

Use the script again.
